version: '3.8'

services:
    docling:
        image: docling:latest
        container_name: docling
        restart: always
        ports:
            - "8080:8080"
        environment:
            - ENV=production